### PR TITLE
HCG <=> HWB support added

### PR DESCRIPTION
**Pull request by acterhd**
Hello. I added support for HWB <=> HCG. 
No tests. But I checked by myself.

### CODE REVIEW

**Comment by dfcreative** [comment]
Thanks!
Closed by efef83921adfd482f74a654eee074311d47dfaf3

**Comment by acterhd** [comment]
I'm sorry.

**Comment by dfcreative** [comment]
1. Next time write tests (it’s 2016).
2. Turn on trimming trailing whitespaces in your editor.

**Comment by acterhd** [comment]
I use notepad++, or Atom. I don't know what editor to use...

**Comment by dfcreative** [comment]
Try sublime text, it is fastest still, comparing to atom/others.

**Comment by acterhd** [comment]
I want to speak by skype, я хочу поговорить по скайпу. Ты не занят?

**Pull request closed without merging**
