### PR TITLE
Fixed HCG, added tests (pass 2)

### PR DESCRIPTION
**Pull request by acterhd**
Sorry for slow

### CODE REVIEW

**Comment by acterhd** [comment]
I have question: how strictly loop?

**Comment by dfcreative** [comment]
Don’t get the question, reformulate please?

**Comment by acterhd** [comment]
I in tests get bug with "360". Need instead of 360 get 0.

**Comment by dfcreative** [comment]
Just `mod(n, 360)`, if `n = 360; mod(n, 360); //0`

**Comment by acterhd** [comment]
But already moded.

**Comment by dfcreative** [comment]
Could you please explain the code-case fully, I don’t get what you mean, sorry.

**Comment by acterhd** [comment]
I'm go sleep. 
```
it('rgb → hcg', function () {
		assert.deepEqual(round(s.rgb.hcg([255, 0, 0])), [ 360, 100, 0 ]);
		
		assert.deepEqual(round(s.rgb.hcg([128, 0, 0])),  [ 360, 50, 0 ]);
		assert.deepEqual(round(s.rgb.hcg([255, 128, 128])),[ 360, 50, 100 ] );
		assert.deepEqual(round(s.rgb.hcg([192, 64, 64])), [ 360, 50, 50 ]);
		
		assert.deepEqual(round(s.rgb.hcg([255, 255, 255])), [ 0, 0, 100 ]);
		assert.deepEqual(round(s.rgb.hcg([128, 128, 128])), [ 0, 0, 50 ]);
		assert.deepEqual(round(s.rgb.hcg([ 0, 0, 0 ])), [0, 0, 0]);
	});
```

**Pull request merged**
