### PR TITLE
Minified HCG, HSV, HSL and HWB functions

### PR DESCRIPTION
**Pull request by acterhd**
Hello. I made mini functions of these. 
Here is original. 
https://github.com/acterhd/hcg-color/tree/master/convert

### CODE REVIEW

**Comment by dfcreative** [comment]
Please stick to the original formatting, es3 and pass the tests.

**Comment by acterhd** [comment]
I wanted ES6 syntax... :(

**Comment by acterhd** [comment]
I reformatted HSV, HSL, HCG, HWB.

**Comment by dfcreative** [comment]
Tabs vs spaces. Original formatting is tabs. Also I am not sure about contracting the formulas. They are taken from default sources, like wiki, and contracting them might puzzle reader, not familiar with the color-space models. Is there any performane improvement?
Though I see they might be good for shaders, as there are way less conditions. So maybe just commit it to 'gl-color-space'? I will be glad to start/contribute to that.

**Comment by acterhd** [comment]
In GLSL will hardly - they have no indexOf, or array functional.

**Comment by dfcreative** [comment]
Well there is a good reference for shader conversions [here](http://www.chilliant.com/rgb2hsv.html).
As for the PR, I am not sure what are the profits of merging it. Current rgb/hsl/hsv/hwb code is default from wiki/referenced sources, so it is easy to read and compare with the reference. I don’t see any wins from the shorter version, as for me it is less readable, is it faster? Calling `array.indexOf` seems to be really bad idea here, it is cheaper to compare per-element, in terms of performance.
I don’t mind modifying _hcg.js_, but as for other spaces there should be a good argument why.
And once again, **indentation should be tabs, same as the original**.

**Pull request closed without merging**
